# apiVersion: v1
# kind: Service
# metadata:
#   name: simple-node-js-pod
# spec:
#   ports:
#     - port: 5001
#       targetPort: 8200
#       nodePort: 30001
#   type: NodePort
#   selector:
#     app: simple-node-js
apiVersion: v1
kind: Service
metadata:
  name: simple-node-js-pod
spec:
  ports:
    - port: 5001
      targetPort: 8200
  type: LoadBalancer
  selector:
    app: simple-node-js
